// import React from "react";

export type PrivacyPolicyProps = {
  companyName?: string;
  domain?: string;
  supportEmail?: string;
  effectiveDate?: string; // e.g., "August 18, 2025"
  className?: string;
};

/**
 * Privacy Policy component for WattMatrix-style IoT SaaS.
 * - Tailwind CSS classes throughout
 * - Smooth in-page navigation, print button, and accessible headings
 * - Replace props to customize for your brand
 */
export default function PrivacyPolicy({
  companyName = "WattMatrix",
  domain = "WattMatrix.io",
  supportEmail = "support@wattmatrix.io",
  // effectiveDate = "[Insert Date]",
  className = "",
}: PrivacyPolicyProps) {
  const siteUrl = `https://${domain}`;

  return (
    <div className={"bg-gray-50 text-primary antialiased " + className}>
      {/* Top Bar */}
      {/* <header className="bg-white border-b sticky top-0 z-40">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <a href={siteUrl} className="text-xl font-semibold tracking-tight" aria-label={`${companyName} home`}>
            {companyName}
          </a>
          <div className="flex items-center gap-2 print:hidden">
            <a href="#contact" className="text-sm px-3 py-2 rounded-lg border hover:bg-gray-50">Contact</a>
            <button onClick={() => window.print()} className="text-sm px-3 py-2 rounded-lg bg-gray-900 text-white hover:opacity-90">
              Print
            </button>
          </div>
        </div>
      </header> */}

      {/* Hero */}
      <section className="bg-gradient-to-b from-white to-gray-50">
        <div className=" mx-auto px-4 sm:px-6 lg:px-8 py-10">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Privacy Policy</h1>
          {/* <p className="mt-2 text-gray-600">
            Effective Date: <span className="font-medium">{effectiveDate}</span>
          </p> */}
          <p className="mt-1 text-gray-600">
            Website: {" "}
            <a href={siteUrl} className="text-gray-900 underline">
              {domain}
            </a>
          </p>
          <p className="mt-6 text-gray-700">
            {companyName} ("Company", "we", "our", or "us") values your privacy. This Privacy Policy
            explains how we collect, use, store, and protect your information when you use our website,
            software, IoT devices, and related services (collectively, the "Services").
          </p>
        </div>
      </section>

      {/* Content Card */}
      <main className=" mx-auto px-4 sm:px-6 lg:px-8 pb-16">
        <article className="bg-white rounded-2xl shadow-sm border p-6 sm:p-10">
          {/* On this page */}
          <nav className="mb-8 print:hidden" aria-label="On this page">
            <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider">On this page</h2>
            <ol className="mt-3 grid sm:grid-cols-2 gap-2 text-sm list-decimal list-inside">
              <li><a className="underline" href="#info-we-collect">Information We Collect</a></li>
              <li><a className="underline" href="#how-we-use">How We Use Your Information</a></li>
              <li><a className="underline" href="#storage-security">Data Storage & Security</a></li>
              <li><a className="underline" href="#third-parties">Third-Party Services</a></li>
              <li><a className="underline" href="#user-rights">User Rights</a></li>
              <li><a className="underline" href="#cookies">Cookies & Tracking</a></li>
              <li><a className="underline" href="#data-sharing">Data Sharing</a></li>
              <li><a className="underline" href="#children">Children’s Privacy</a></li>
              <li><a className="underline" href="#changes">Changes to This Policy</a></li>
              <li><a className="underline" href="#contact">Contact Us</a></li>
            </ol>
          </nav>

          {/* 1. Information We Collect */}
          <section id="info-we-collect" className="scroll-mt-24">
            <h2 className="text-2xl text-primary  font-semibold">1. Information We Collect</h2>
            <p className="mt-3 text-gray-700">When you use our Services, we may collect the following types of information:</p>
            <ul className="mt-4 space-y-3 text-gray-700 list-disc pl-5">
              <li>
                <span className="font-medium">Account Information:</span> If you register or log in using <span className="font-medium">Google Login</span>, we collect your name, email address, and profile details provided by Google.
              </li>
              <li>
                <span className="font-medium">Device &amp; Service Data:</span> We collect data generated by your IoT devices, including sensor readings, alarms, logs, and device usage statistics.
              </li>
              <li>
                <span className="font-medium">Payment Information:</span> Payments are processed securely through <span className="font-medium">GoPay</span> or other third-party providers. We do not store your credit/debit card details on our servers.
              </li>
              <li>
                <span className="font-medium">Communication Data:</span> If you contact us for support, we may store messages, emails, or inquiries.
              </li>
            </ul>
            <p className="mt-4 text-gray-700">
              We <span className="font-semibold">do not sell, rent, or share personal data</span> with third parties for marketing purposes.
            </p>
          </section>

          <hr className="my-8" />

          {/* 2. How We Use Your Information */}
          <section id="how-we-use" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">2. How We Use Your Information</h2>
            <p className="mt-3 text-gray-700">We use the collected information for the following purposes:</p>
            <ul className="mt-4 space-y-3 text-gray-700 list-disc pl-5">
              <li>To provide and improve our IoT monitoring and alarm services.</li>
              <li>To authenticate users via Google Login.</li>
              <li>To process subscription payments securely via GoPay.</li>
              <li>To detect, analyze, and display real-time device data.</li>
              <li>To provide customer support and resolve issues.</li>
              <li>To ensure the security and integrity of our systems.</li>
            </ul>
          </section>

          <hr className="my-8" />

          {/* 3. Data Storage & Security */}
          <section id="storage-security" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">3. Data Storage &amp; Security</h2>
            <ul className="mt-4 space-y-3 text-gray-700 list-disc pl-5">
              <li>All IoT device data and user information is stored securely on our servers.</li>
              <li>We apply industry-standard security practices, including encryption and restricted access.</li>
              <li>Personal information is retained only as long as necessary for providing services.</li>
            </ul>
          </section>

          <hr className="my-8" />

          {/* 4. Third-Party Services */}
          <section id="third-parties" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">4. Third-Party Services</h2>
            <p className="mt-3 text-gray-700">Our Services use the following third-party providers:</p>
            <ul className="mt-4 space-y-3 text-gray-700 list-disc pl-5">
              <li>
                <span className="font-medium">Google Login (OAuth):</span> For secure authentication. Please review Google’s Privacy Policy at {" "}
                <a className="underline" href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">
                  https://policies.google.com/privacy
                </a>
                .
              </li>
              <li>
                <span className="font-medium">GoPay:</span> For payment processing. Please review GoPay’s Privacy Policy at {" "}
                <a className="underline" href="https://www.gopay.com/en/privacy-policy" target="_blank" rel="noopener noreferrer">
                  https://www.gopay.com/en/privacy-policy
                </a>
                .
              </li>
            </ul>
            <p className="mt-4 text-gray-700">These providers may process your information according to their own privacy policies.</p>
          </section>

          <hr className="my-8" />

          {/* 5. User Rights */}
          <section id="user-rights" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">5. User Rights</h2>
            <p className="mt-3 text-gray-700">You have the right to:</p>
            <ul className="mt-4 space-y-3 text-gray-700 list-disc pl-5">
              <li>Access and update your personal information.</li>
              <li>Request deletion of your account and stored data.</li>
              <li>Withdraw consent for data processing where applicable.</li>
            </ul>
            <p className="mt-4 text-gray-700">
              To exercise these rights, please contact us at {" "}
              <a href={`mailto:${supportEmail}`} className="underline">
                {supportEmail}
              </a>
              .
            </p>
          </section>

          <hr className="my-8" />

          {/* 6. Cookies & Tracking */}
          <section id="cookies" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">6. Cookies &amp; Tracking</h2>
            <p className="mt-3 text-gray-700">
              We may use cookies and similar technologies to improve user experience, analyze usage, and secure our Services. Users can control cookies through browser settings.
            </p>
          </section>

          <hr className="my-8" />

          {/* 7. Data Sharing */}
          <section id="data-sharing" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">7. Data Sharing</h2>
            <p className="mt-3 text-gray-700">
              We may share information only when required by law, to protect our rights, or to provide services through trusted partners (e.g., payment providers).
            </p>
            <p className="mt-3 text-gray-700">
              We <span className="font-semibold">do not sell or trade</span> your personal data to advertisers or unauthorized third parties.
            </p>
          </section>

          <hr className="my-8" />

          {/* 8. Children’s Privacy */}
          <section id="children" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">8. Children’s Privacy</h2>
            <p className="mt-3 text-gray-700">
              Our Services are not intended for children under 13. We do not knowingly collect personal information from children.
            </p>
          </section>

          <hr className="my-8" />

          {/* 9. Changes to This Policy */}
          <section id="changes" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">9. Changes to This Policy</h2>
            <p className="mt-3 text-gray-700">
              We may update this Privacy Policy from time to time. Any changes will be posted on this page with a revised “Effective Date.”
            </p>
          </section>

          <hr className="my-8" />

          {/* 10. Contact Us */}
          <section id="contact" className="scroll-mt-24">
            <h2 className="text-2xl font-semibold text-primary">10. Contact Us</h2>
            <p className="mt-3 text-gray-700">If you have any questions or concerns about this Privacy Policy, please contact us at:</p>
            <div className="mt-4 grid sm:grid-cols-2 gap-3 text-primary">
              <p>
                📧 {" "}
                <a href={`mailto:${supportEmail}`} className="underline">
                  {supportEmail}
                </a>
              </p>
              <p>
                🌐 {" "}
                <a href={siteUrl} target="_blank" rel="noopener noreferrer" className="underline">
                  {domain}
                </a>
              </p>
            </div>
          </section>
        </article>

        <p className="mt-6 text-xs text-gray-500">
          This Privacy Policy covers Google Login (account info), GoPay payments, and IoT device data handling for {companyName}.
        </p>
      </main>

      {/* <footer className="border-t bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 text-sm text-gray-600 flex items-center justify-between">
          <span>
            &copy; {new Date().getFullYear()} {companyName}. All rights reserved.
          </span>
          <a href="#" className="print:hidden underline">
            Back to top ↑
          </a>
        </div>
      </footer> */}
    </div>
  );
}
